url: "https://otherpeopleucsd.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/dandelion_kisses" # the subpath of your site, e.g. /blog
title: "Other People" # the name of your site, e.g. ACME Corp.
future: true