---
label: Default
hide_body: true
fields:
- name: artist_name
  type: text
  config:
    required: false
  label: piece name
- name: artist
  type: text
  config:
    required: false
  label: artist
- name: year
  type: text
  config:
    required: false
  label: year
- name: image
  type: file
  config:
    maxSize: 250
  label: image
- name: newsletter_background
  type: file
  config:
    maxSize: 250
  label: newsletter background
- name: layout
  type: text
  config:
    required: false
  label: layout
  default: default
- name: title
  type: text
  config:
    required: false
  label: title
pages:
- index.md
